const RASHI_LORDS=['मंगल','शुक्र','बुध','चन्द्र','सूर्य','बुध','शुक्र','मंगल','गुरु','शनि','शनि','गुरु'];
const ELEMENT_VARNA=['क्षत्रिय','वैश्य','वैश्य','ब्राह्मण','क्षत्रिय','वैश्य','वैश्य','ब्राह्मण','क्षत्रिय','शूद्र','वैश्य','ब्राह्मण'];
const VARNA_RANK={शूद्र:1,वैश्य:2,क्षत्रिय:3,ब्राह्मण:4};
const GANA=['देव','मानुष्य','राक्षस'];
const NADI=['आदि','मध्य','अन्त्य'];
const YONI=['घोडा','हात्ती','भेडा','सर्प','सर्प','कुकुर','बिरालो','भेडा','बिरालो','मुसा','मुसा','गाई','भैंसी','बाघ','भैंसी','बाघ','मृग','मृग','कुकुर','बाँदर','नेवला','बाँदर','सिंह','घोडा','सिंह','गाई','हात्ती'];
const YONI_ENEMIES=[['घोडा','भैंसी'],['हात्ती','सिंह'],['भेडा','बाँदर'],['सर्प','नेवला'],['कुकुर','मृग'],['बिरालो','मुसा'],['गाई','बाघ']];
const FRIEND={सूर्य:{मित्र:['चन्द्र','मंगल','गुरु'],शत्रु:['शुक्र','शनि']},चन्द्र:{मित्र:['सूर्य','बुध'],शत्रु:[]},मंगल:{मित्र:['सूर्य','चन्द्र','गुरु'],शत्रु:['बुध']},बुध:{मित्र:['सूर्य','शुक्र'],शत्रु:['चन्द्र']},गुरु:{मित्र:['सूर्य','चन्द्र','मंगल'],शत्रु:['बुध','शुक्र']},शुक्र:{मित्र:['बुध','शनि'],शत्रु:['सूर्य','चन्द्र']},शनि:{मित्र:['बुध','शुक्र'],शत्रु:['सूर्य','चन्द्र','मंगल']}};
const GANA_MATRIX={देव:{देव:6,मानुष्य:5,राक्षस:1},मानुष्य:{देव:5,मानुष्य:6,राक्षस:0},राक्षस:{देव:1,मानुष्य:0,राक्षस:6}};
const signDistance=(a,b)=>((b-a+12)%12)+1;
const scoreTara=(a,b)=>{const n=signDistance(a,b);return [1,3,5,7].includes(((n-1)%9)+1)?1:0};
const yoniScore=(a,b)=>a===b?4:YONI_ENEMIES.some(([x,y])=>(a===x&&b===y)||(a===y&&b===x))?0:2;
const grahaScore=(a,b)=>{if(a===b)return 5;const x=FRIEND[a]||{},y=FRIEND[b]||{};if((x.mitra||[]).includes(b)|| (y.mitra||[]).includes(a))return 4;if((x.shatru||[]).includes(b)&&(y.shatru||[]).includes(a))return 0;return 3};
function taraPoints(a,b){const x=scoreTara(a.moonNakshatra.index,b.moonNakshatra.index),y=scoreTara(b.moonNakshatra.index,a.moonNakshatra.index);return x&&y?3:(x||y)?1:0}
function bhakootPoints(a,b){const d1=signDistance(a.rashi.sign,b.rashi.sign),d2=signDistance(b.rashi.sign,a.rashi.sign),bad=(d1===2&&d2===12)||(d1===5&&d2===9)||(d1===6&&d2===8);return bad?0:7}
function vashyaGroup(s){if(s===4)return'वनचर';if(s===7)return'कीट';if([3,11].includes(s))return'जलचर';if([0,1,8,9].includes(s))return'चतुष्पद';return'मानुष्य'}
function vashyaPoints(a,b){const x=vashyaGroup(a.rashi.sign),y=vashyaGroup(b.rashi.sign);if(x===y)return 2;if((x==='मानुष्य'&&y==='चतुष्पद')||(x==='चतुष्पद'&&y==='मानुष्य'))return 1;return 0}
function manglik(chart){const mars=chart.planets.find(p=>p.name==='मंगल');const housesFrom=s=>((mars.sign-s+12)%12)+1;const lagna=housesFrom(chart.ascendant.sign),moon=housesFrom(chart.rashi.sign);const venus=housesFrom(chart.planets.find(p=>p.name==='शुक्र')?.sign??chart.ascendant.sign);return{fromLagna:lagna,fromMoon:moon,fromVenus:venus,activeFromLagna:[1,4,7,8,12].includes(lagna),activeFromMoon:[1,4,7,8,12].includes(moon),activeFromVenus:[1,4,7,8,12].includes(venus),score:[lagna,moon,venus].filter(h=>[1,4,7,8,12].includes(h)).length}}
export function calculateMatching(a,b){const varna=Math.min(1,Math.max(0,VARNA_RANK[ELEMENT_VARNA[a.rashi.sign]]>=VARNA_RANK[ELEMENT_VARNA[b.rashi.sign]]?1:0));const vashya=vashyaPoints(a,b);const tara=taraPoints(a,b);const yoni=yoniScore(YONI[a.moonNakshatra.index],YONI[b.moonNakshatra.index]);const maitri=grahaScore(RASHI_LORDS[a.rashi.sign],RASHI_LORDS[b.rashi.sign]);const gana=GANA_MATRIX[GANA[a.moonNakshatra.index%3]][GANA[b.moonNakshatra.index%3]];const bhakoot=bhakootPoints(a,b);const nadi=NADI[a.moonNakshatra.index%3]===NADI[b.moonNakshatra.index%3]?0:8;const items=[['वर्ण',varna,1,'चन्द्र राशिको वर्ण'],['वश्य',vashya,2,'राशि समूह'],['तारा',tara,3,'जन्म नक्षत्र दूरी'],['योनि',yoni,4,'नक्षत्र योनि'],['ग्रह मैत्री',maitri,5,'राशि स्वामी सम्बन्ध'],['गण',gana,6,'नक्षत्र गण'],['भकूट',bhakoot,7,'चन्द्र राशि सम्बन्ध'],['नाडी',nadi,8,'नक्षत्र नाडी']];const total=items.reduce((s,x)=>s+x[1],0);const ma= manglik(a),mb=manglik(b);return{items,total,max:36,percentage:Math.round(total/36*100),manglik:{a:ma,b:mb,balanced:ma.score===mb.score,comment:ma.score===mb.score?'मंगलको प्रभाव स्तर बराबर छ।':'मंगलको प्रभाव स्तर फरक छ; परम्परागत कुन्डली मिलानमा थप नियम जाँचिन्छ।'},summary:total>=28?'उच्च गुण मिलान':total>=18?'मध्यम गुण मिलान':'कम गुण मिलान',note:'अष्टकूट गुण मिलान परम्परागत ज्योतिषीय पद्धति हो। विभिन्न परम्परामा नियम, नाडी/भकूट दोष र मंगल दोषका अपवाद फरक हुन सक्छन्। यसलाई वैज्ञानिक compatibility test वा विवाहको निश्चित भविष्यवाणी नमान्नुहोस्।'}
export{RASHI_LORDS,ELEMENT_VARNA,GANA,NADI,YONI};
